Repository nbcamp-14-team/newsoop, pull requests merged in 2023-10, with the labels that each got.

#6 파일생성
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/MainActivity.kt
  app/src/main/java/com/nbcamp_14_project/MainFragment.kt
  app/src/main/java/com/nbcamp_14_project/MainViewPagerAdapter.kt
  app/src/main/java/com/nbcamp_14_project/api/NewsCollector.kt
  app/src/main/res/drawable/politician.png
  app/src/main/res/layout/activity_main.xml
Labels: feature

#7 [Design]: 로그인액티비티 디자인
  .idea/.name
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/data/LoginDataSource.kt
  app/src/main/java/com/nbcamp_14_project/data/LoginRepository.kt
  app/src/main/java/com/nbcamp_14_project/data/Result.kt
  app/src/main/java/com/nbcamp_14_project/data/model/LoggedInUser.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoggedInUserView.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginFormState.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginResult.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModelFactory.kt
  app/src/main/res/drawable/ic_google.png
  app/src/main/res/drawable/ic_kakao.png
  app/src/main/res/drawable/ic_naver.png
  app/src/main/res/drawable/img_app_logo.png
  app/src/main/res/drawable/img_logo.png
  app/src/main/res/layout-w1240dp/activity_login.xml
  app/src/main/res/layout-w936dp/activity_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: UI

#8 [DESIGN] : DetailActivity UI 작성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/DetailActivity.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/muhandojeon.png
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: UI

#10 [DESIGN] : Detailactivity UI 작성
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/drawable/ic_mic.xml
  app/src/main/res/drawable/ic_share.xml
Labels: UI

#11 [FIX] LoginActivity
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
Labels: fix

#12 Mainpage/design
  .idea/.name
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/DetailActivity.kt
  app/src/main/java/com/nbcamp_14_project/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/MainActivity.kt
  app/src/main/java/com/nbcamp_14_project/MainFragment.kt
  app/src/main/java/com/nbcamp_14_project/MainViewPagerAdapter.kt
  app/src/main/java/com/nbcamp_14_project/SearchFragment.kt
  app/src/main/java/com/nbcamp_14_project/api/NewsCollector.kt
  app/src/main/java/com/nbcamp_14_project/data/LoginDataSource.kt
  app/src/main/java/com/nbcamp_14_project/data/LoginRepository.kt
  app/src/main/java/com/nbcamp_14_project/data/Result.kt
  app/src/main/java/com/nbcamp_14_project/data/model/LoggedInUser.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoggedInUserView.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginFormState.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginResult.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModelFactory.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_google.png
  app/src/main/res/drawable/ic_kakao.png
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/drawable/ic_mic.xml
  app/src/main/res/drawable/ic_naver.png
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/img_app_logo.png
  app/src/main/res/drawable/img_logo.png
  app/src/main/res/drawable/muhandojeon.png
  app/src/main/res/drawable/politician.png
  app/src/main/res/layout-w1240dp/activity_login.xml
  app/src/main/res/layout-w936dp/activity_login.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_item.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: UI, feature

#15 [FEAT] : API 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/MainFragment.kt
  app/src/main/java/com/nbcamp_14_project/api/NewsCollector.kt
  app/src/main/java/com/nbcamp_14_project/api/NewsDTO.kt
  app/src/main/java/com/nbcamp_14_project/api/RetrofitInstance.kt
Labels: feature

#18 [DESIGN]: 로그인 액티비티
  app/src/main/res/layout-w1240dp/activity_login.xml
  app/src/main/res/layout-w936dp/activity_login.xml
  app/src/main/res/layout/activity_login.xml
Labels: UI

#19 [DESIGN] : detailactivity ui 수정
  app/src/main/res/layout/activity_detail.xml
Labels: UI

#20 [DESIGN] : DetailActivity UI 수정
  app/src/main/res/drawable/btn_detail.xml
  app/src/main/res/drawable/ic_like.png
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/drawable/ic_mic.png
  app/src/main/res/drawable/ic_mic.xml
  app/src/main/res/drawable/ic_share.png
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/img_muhandojeon.png
  app/src/main/res/layout/activity_detail.xml
Labels: UI

#24 [FEAT] : HomeFragment에 recyclerView AutoScroll 구현
  app/src/main/java/com/nbcamp_14_project/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/Main/MainFragmentModel.kt
  app/src/main/java/com/nbcamp_14_project/Main/MainFragmentViewModel.kt
  app/src/main/java/com/nbcamp_14_project/Utils.kt
  app/src/main/java/com/nbcamp_14_project/domain/GetSearchNewsUseCase.kt
  app/src/main/java/com/nbcamp_14_project/home/Home.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainViewPagerAdapter.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/item_recyclerview_main_fragment.xml
Labels: feature

#26 Feat/crolling
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/Utils.kt
  app/src/main/java/com/nbcamp_14_project/home/Home.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeHeadLineAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeNewsAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/item_recyclerview_main_fragment.xml
  app/src/main/res/layout/item_rv_news_main.xml
  settings.gradle.kts
Labels: feature

#31 [FEAT]: 로그인, 회원가입 기능 [DESIGN]: 회원가입페이지
  .idea/gradle.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/data/LoginDataSource.kt
  app/src/main/java/com/nbcamp_14_project/data/LoginRepository.kt
  app/src/main/java/com/nbcamp_14_project/data/Result.kt
  app/src/main/java/com/nbcamp_14_project/data/model/FirebaseUserData.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoggedInUserView.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginFormState.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginResult.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModelFactory.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  build.gradle.kts
Labels: UI, feature

#32 [FEAT] : DetailActivity MVVM 패턴 구현
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/DetailActivity.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailActivity.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailInfo.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/Home.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#34 [DESIGN]: 회원가입 페이지 디자인
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/res/layout/activity_sign_up.xml
Labels: UI

#36 [FEAT] : DetailActivity 원문 보기 , 애니매이션 기능
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/detail/DetailActivity.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailInfo.kt
  app/src/main/java/com/nbcamp_14_project/home/Home.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
  app/src/main/res/anim/slide_in_up.xml
  app/src/main/res/anim/slide_out_down.xml
  app/src/main/res/anim/stay.xml
Labels: feature

#41 [FEAT]: googlelogin 구현
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/data/LoginRepository.kt
  app/src/main/java/com/nbcamp_14_project/data/model/User.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/et_border_radius.xml
  app/src/main/res/drawable/et_border_radius_red.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: feature

#44 자잘한 버그 수정
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/Utils.kt
  app/src/main/java/com/nbcamp_14_project/home/Home.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchRepository.kt
  app/src/main/res/drawable/btn_home.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/item_loading.xml
  app/src/main/res/layout/item_rv_news_main.xml
Labels: bug, feature, fix

#48 [FEAT] : DetailFragment 북마크 삭제 기능
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/res/drawable/ic_like.png
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: feature

#49 [FEAT] : DetailFragment 북마크 삭제 기능
  app/src/main/res/drawable/ic_check.xml
Labels: feature

#52 [FIX] : HomeFragment 수정
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/Utils.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerFragment.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainViewPagerAdapter.kt
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/values/style.xml
Labels: bug

#55 [[REFACTOR] : loginActivity
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/res/values/strings.xml
Labels: fix

#57 [FEAT]: firestore
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/data/LoginRepository.kt
  app/src/main/java/com/nbcamp_14_project/data/model/User.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
Labels: feature

#60 [FEAT] : DetailFragment FireStore 기능 구현
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/layout/fragment_favorite.xml
Labels: feature

#64 [FEAT] : Login과 FavoriteFragment Firestore 연결
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
Labels: feature

#66 [FEAT]: 회원가입시 파이어스토어에 정보 저장
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/category_dialog.xml
Labels: feature

#69 [FEAT]: 로그인 수정
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
Labels: fix

#70 [Fix]: 임시커밋
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
Labels: fix

#72 [FEAT] : FavoriteFragment Login기능 구현
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
  app/src/main/res/layout/fragment_favorite.xml
  build.gradle.kts
Labels: feature

#73 [FEAT],[DESIGN]: CategoryFragment
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/CategoryFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/category_dialog.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: UI, feature

#78 [FEAT] : FavoriteFragment Login, Logout 기능 구현, Login시 이름 데이터 받기
  app/src/main/java/com/nbcamp_14_project/detail/DetailInfo.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
Labels: feature

#79 [FEAT]: 이메일 중복체크
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/CategoryFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/anim/shake.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/colors.xml
Labels: feature

#81 [Feat]: 회원가입 유효성 검사
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
Labels: feature

#83 [Feat]: 로그인 유효성검사
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
Labels: feature

#85 [FIX]:DetailPage pubdate 수정
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
Labels: fix

#86 [Fix]: 회원가입 유효성검사 수정
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
Labels: fix

#90 [DESIGN]: 로그인, 회원가입페이지 디자인
  app/src/main/res/drawable/bg_login.xml
  app/src/main/res/drawable/et_round_white.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/colors.xml
Labels: UI

#91 [DESIGN]: 디자인수정
  app/src/main/res/drawable/bg_signup.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: UI

#92 [FIX]: 회원가입페이지 유효성 수정, 배경수정
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/res/layout/activity_sign_up.xml
Labels: fix

#95 Design/home
  app/src/androidTest/java/com/nbcamp_14_project/ExampleInstrumentedTest.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailInfo.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeHeadLineAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeNewsAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerFragment.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainActivity.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchViewModel.kt
  app/src/main/res/drawable/iv_home.xml
  app/src/main/res/layout/item_rv_news_main.xml
  app/src/test/java/com/nbcamp_14_project/ExampleUnitTest.kt
Labels: documentation, feature

#97 [DESIGN] : DetailFragment, FavoriteFragment UI 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainActivity.kt
  app/src/main/res/drawable/bg_round.xml
  app/src/main/res/drawable/btn_white_border.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/img_person.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_favorite.xml
Labels: UI, feature

#98 [FIX]: 테마수정
  app/src/main/res/values/themes.xml
Labels: fix

#99 [FIX]: 프래그먼트 간섭 최소화
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: bug

#100 [DESIGN]: 메터리얼 버튼으로 변경
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
Labels: UI

#103 [DESIGN] : Splash 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/SplashActivity.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/btn_white_border.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_favorite.xml
  build.gradle.kts
Labels: UI

#104 [DESIGN] : Splash 화면 추가
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
Labels: UI

#106 [Fix] :구글 로그인 시 FavoriteFragment에 바로 적용 안되는거 수정
  app/src/main/java/com/nbcamp_14_project/SplashActivity.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/res/drawable/iv_home.xml
Labels: fix

#107 [Fix] :Splash UI 수정
  app/src/main/res/layout/activity_splash.xml
Labels: fix

#109 Design/home
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: fix

#111 [FIX]: DetailFragment 북마크 작동 시 searchFragment 리사이클러뷰 스위치에 작동 안되던 부분 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailInfo.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerFragment.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainActivity.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_viewpager_home.xml
Labels: fix

#120 [FIX] : DebateFragment에 Firestore 적용
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt
Labels: fix

#121 [FIX] : DebateFragment에 Firestore 적용
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/res/drawable/ic_agree.xml
  app/src/main/res/drawable/ic_opposite.xml
  app/src/main/res/layout/fragment_debatedetail.xml
Labels: feature, fix

#122 [FIX] : DebateFragment에 Firestore 적용
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt
  app/src/main/res/layout/fragment_debatedetail.xml
  app/src/main/res/layout/item_debatedetail.xml
Labels: fix

#124 [FIX]: 리사이클러뷰 로딩 안전장치 구현
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeNewsAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainActivity.kt
  app/src/main/res/drawable/ic_debate.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_news.xml
  app/src/main/res/drawable/ic_selected_debate.xml
  app/src/main/res/drawable/ic_selected_home.xml
  app/src/main/res/drawable/ic_selected_news.xml
  app/src/main/res/drawable/ic_selected_search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_viewpager_home.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: fix

#125 [DESIGN]: 로그인, 회원가입, 카테고리 UI 변경
  app/src/main/java/com/nbcamp_14_project/ui/login/CategoryFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/res/drawable/et_round_white.xml
  app/src/main/res/drawable/ic_google.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: UI

#126 [FEAT]: 이메일 로그인 시 카테고리 전달
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/data/model/User.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/CategoryFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_category.xml
Labels: feature
