Repository nbcamp-14-team/newsoop, pull requests merged in 2023-11, with the labels that each got.

#128 [FEAT] : DebateDetailFragment 댓글 기능 구현
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateViewModel.kt
Labels: feature

#129 비밀번호 재설정 페이지 디자인
  app/src/main/java/com/nbcamp_14_project/ui/login/FixPwFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_fix_pw.xml
Labels: UI

#130 [FEAT] : DebateDetailFragment 댓글 기능 구현
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailItem.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt
  app/src/main/res/layout/item_debatedetail.xml
Labels: feature

#135 [FIX]: 웹뷰 사용시 이미지 안뜨던 현상 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nbcamp_14_project/newspaper/NewspaperDialog.kt
  app/src/main/java/com/nbcamp_14_project/newspaper/NewspaperRepositiory.kt
Labels: bug

#136 [FIX]: 로고 빠진 내용 수정
  app/src/main/java/com/nbcamp_14_project/newspaper/NewspaperFragment.kt
  app/src/main/java/com/nbcamp_14_project/newspaper/NewspaperRepositiory.kt
  app/src/main/res/drawable/logo_edaily.png
  app/src/main/res/drawable/logo_thejoongang.png
  app/src/main/res/drawable/logo_yna.png
Labels: bug

#137 [FEAT]: 뉴스사별 페이지 애니메이션 추가
  app/src/main/java/com/nbcamp_14_project/newspaper/NewspaperDialog.kt
  app/src/main/java/com/nbcamp_14_project/newspaper/NewspaperRepositiory.kt
  app/src/main/res/anim/none.xml
Labels: feature

#139 [FEAT] : DebateDetailFragment 찬성, 반대 기능 구현
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/res/drawable/ic_agreex.xml
  app/src/main/res/drawable/ic_oppositex.xml
  app/src/main/res/layout/fragment_debatedetail.xml
Labels: feature

#140 [FIX] : DebateDetailFragment 찬성, 반대 기능 수정
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/res/layout/fragment_debatedetail.xml
Labels: fix

#145 구글 로그인시 카테고리 기능 구현했습니다.
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/CategoryFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/FixPwFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/blur_background.xml
  app/src/main/res/drawable/ic_change.xml
  app/src/main/res/drawable/signup_scroll_top_outline.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_fix_pw.xml
  app/src/main/res/values/colors.xml
Labels: UI, feature, fix

#148 선호 카테고리 갱신, 보여주기 기능
  app/src/main/java/com/nbcamp_14_project/data/LoginRepository.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/layout/fragment_favorite.xml
Labels: feature, fix

#150 [FEAT] : DebateDetailFragment Spinner 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/drawable/spinner_selector.xml
  app/src/main/res/layout/dialog_debate.xml
  app/src/main/res/layout/fragment_debatedetail.xml
  app/src/main/res/values/strings.xml
Labels: feature

#152 [FIX]: 북마크 기능 버그 수정
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailInfo.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/res/layout/item_recyclerview_main_fragment.xml
Labels: bug

#154 [DESIGN] : DebateFragment UI 수정
  .idea/misc.xml
  app/src/main/res/drawable/ic_cancel_24.xml
  app/src/main/res/layout/dialog_debatedetail.xml
  app/src/main/res/layout/fragment_debate.xml
  app/src/main/res/layout/fragment_debatedetail.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/item_debate.xml
  app/src/main/res/layout/item_debatedetail.xml
  app/src/main/res/layout/item_debatedetail2.xml
  app/src/main/res/values/strings.xml
Labels: feature

#156 [FEAT]: 홈 프래그먼트 추천 탭 활성
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerViewModel.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainActivity.kt
  app/src/main/java/com/nbcamp_14_project/newspaper/NewspaperDialog.kt
  app/src/main/java/com/nbcamp_14_project/newspaper/NewspaperRepositiory.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/CategoryFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature

#157 [DESIGN] : DebateFragment, DebateDetailFragment UI 수정
  .idea/misc.xml
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateViewModel.kt
  app/src/main/res/layout/dialog_debate.xml
  app/src/main/res/layout/fragment_debate.xml
  app/src/main/res/layout/fragment_debate_plus.xml
  app/src/main/res/layout/fragment_debatedetail.xml
  app/src/main/res/layout/item_debate.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#158 추천 탭 수정
  app/src/main/java/com/nbcamp_14_project/api/RetrofitInstance.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerRepositiory.kt
  app/src/main/res/layout/fragment_debate.xml
Labels: bug

#160 [FEAT] : DebateFragment 검색 기능 구현
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/dialog_rounded_bg.xml
  app/src/main/res/drawable/et_round_white2.xml
  app/src/main/res/drawable/ic_blue.xml
  app/src/main/res/drawable/ic_red.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/dialog_debate.xml
  app/src/main/res/layout/fragment_debate.xml
  app/src/main/res/layout/fragment_debatedetail.xml
  app/src/main/res/layout/item_debate.xml
  app/src/main/res/layout/item_debatedetail.xml
  app/src/main/res/layout/item_debatedetail2.xml
  app/src/main/res/values/style.xml
Labels: feature

#161 [DESIGN] : drawble 파일 추가
  app/src/main/res/drawable/ic_plus_24px.xml
Labels: fix

#162 [FIX] : 팔로우 기자 어뎁터 연결
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteRepositiory.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FollowingListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerFragment.kt
  app/src/main/res/layout/fragment_debate.xml
  app/src/main/res/layout/fragment_favorite.xml
Labels: bug, fix

#163 [DESIGN] : DebateFragment, DebateDetailFragment UI 수정
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateItem.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
  app/src/main/res/drawable/baseline_person_outline_24.xml
  app/src/main/res/drawable/ic_agree.xml
  app/src/main/res/drawable/ic_agreex.xml
  app/src/main/res/drawable/ic_blue.xml
  app/src/main/res/drawable/ic_opposite.xml
  app/src/main/res/drawable/ic_oppositex.xml
  app/src/main/res/drawable/ic_red.xml
  app/src/main/res/layout/dialog_debatedetail.xml
  app/src/main/res/layout/fragment_debate.xml
  app/src/main/res/layout/fragment_debatedetail.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/item_debate.xml
  app/src/main/res/layout/item_debatedetail.xml
  app/src/main/res/layout/item_debatedetail2.xml
  app/src/main/res/values/colors.xml
Labels: feature

#164 기자 팔로잉 기능
  app/src/main/java/com/nbcamp_14_project/data/LoginRepository.kt
  app/src/main/java/com/nbcamp_14_project/data/model/FirebaseUserData.kt
  app/src/main/java/com/nbcamp_14_project/data/model/User.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/ic_change.xml
Labels: feature

#165 [DESIGN] : DebateFragment, DebateDetailFragment 본인만 삭제 가능
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: feature

#167 기자 팔로잉 기능 수정, favorite ui 수정
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteRepositiory.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteViewModel.kt
  app/src/main/res/layout/activity_sign_up.xml
Labels: UI, fix

#168 UI 수정
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/res/layout/fragment_favorite.xml
Labels: fix

#170 favoriteFragment, favorite.xml 수정
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/res/layout/fragment_favorite.xml
Labels: fix

#171 임시 커밋
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeNewsAdapter.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/res/layout/dialog_newspaper.xml
  app/src/main/res/layout/fragment_favorite.xml
Labels: bug

#172 [FEAT]: 구독중 구독하기 버튼 구현
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/mainpage/MainActivity.kt
Labels: feature

#174 기자 팔로잉기능 관련 버그 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FollowingListAdapter.kt
Labels: bug, fix

#176 [FIX] : 앱 아이콘 설정 및 Toast를 Snackbar로 변경
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/ic_main-playstore.png
  app/src/main/java/com/nbcamp_14_project/SignUpActivity.kt
  app/src/main/java/com/nbcamp_14_project/Utils.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/FixPwFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
  app/src/main/res/drawable/ic_main_background.xml
  app/src/main/res/drawable/snackbar_background.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main_round.xml
  app/src/main/res/mipmap-hdpi/ic_main.webp
  app/src/main/res/mipmap-hdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_main_round.webp
  app/src/main/res/mipmap-mdpi/ic_main.webp
  app/src/main/res/mipmap-mdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_main_round.webp
  app/src/main/res/mipmap-xhdpi/ic_main.webp
  app/src/main/res/mipmap-xhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_main_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_main.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_round.webp
  app/src/main/res/values/style.xml
Labels: fix

#178 [FIX] : Splash 화면 변경 및 dimens 추가
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/values-560dpi/dimens.xml
  app/src/main/res/values-xhdpi/dimens.xml
Labels: fix

#179 로그인페이지 텍스트 UI변경
  app/src/main/res/layout/activity_login.xml
Labels: UI

#181 ver.1
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_newspaper.xml
  app/src/main/res/layout/item_rv_newspaper.xml
  app/src/main/res/values-560dpi/dimens.xml
  app/src/main/res/values-xhdpi/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: finish

#184 리펙토링 완료
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerRepositiory.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerViewModel.kt
Labels: documentation, fix

#186 자잘자잘한 버그 수정
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailRepository.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailViewModel.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchViewModel.kt
Labels: bug, fix

#187 [FIX] : 주석처리 및 SearchFragment UI 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/res/layout/fragment_debatedetail.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_item.xml
Labels: feature, fix

#188 [FIX] : 버전 수정
  .idea/deploymentTargetDropDown.xml
  .idea/other.xml
  app/build.gradle.kts
Labels: documentation

#189 [FIX] : 버전 수정
  app/build.gradle.kts
Labels: finish

#190 버전 업
  .idea/deploymentTargetDropDown.xml
  .idea/other.xml
  README.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateListAdapter.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailRepository.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailViewModel.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeRepository.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewModel.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerRepositiory.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeViewPagerViewModel.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchRepository.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_debatedetail.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_item.xml
  app/src/main/res/layout/fragment_search_tag.xml
Labels: finish

#191 [FIX] : 로그인 할 때 추천 탭이 활성화되지 않았던 내용 수정
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/nbcamp_14_project/debate/DebateDetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/debate/DebateFragment.kt
  app/src/main/java/com/nbcamp_14_project/detail/DetailFragment.kt
  app/src/main/java/com/nbcamp_14_project/favorite/FavoriteFragment.kt
  app/src/main/java/com/nbcamp_14_project/home/HomeFragment.kt
  app/src/main/java/com/nbcamp_14_project/search/SearchFragment.kt
  app/src/main/java/com/nbcamp_14_project/ui/login/LoginActivity.kt
Labels: bug

#198 [FIX] : DebateDetailFragment UI 수정
  app/src/main/res/layout/fragment_debatedetail.xml
Labels: fix
